# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('group_img', utils.fields.custom_imagefield.CustomImageField(blank=True, upload_to='group/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_d_date', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=24)),
                ('category_detail', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(max_length=24)),
                ('gu', models.CharField(max_length=24)),
                ('dong', models.CharField(max_length=24)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
