# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20170802_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='modified_d_date',
            new_name='modified_date',
        ),
    ]
