# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20170802_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='group',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
