# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_group_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_introduce',
        ),
    ]
