# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_remove_group_group_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_introduce',
            field=models.TextField(default='그룹소개내용내용'),
            preserve_default=False,
        ),
    ]
