# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_group_group_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
