# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_group_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_introduce',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='member',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
