# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20170823_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='level1',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='region',
            name='level2',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='region',
            name='level3',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
