# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170731_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=24),
        ),
    ]
