# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_member'),
        ('member', '0012_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_group',
        ),
        migrations.AddField(
            model_name='user',
            name='open_group',
            field=models.ManyToManyField(to='group.Group'),
        ),
    ]
