# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20170813_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(default='', max_length=100),
        ),
    ]
