# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_d_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='post_img',
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group.Group'),
        ),
    ]
